version: "3"

services:
    web:
        container_name: authapp
        restart: always
        build: .
        ports:
            - "3001:4000"
        links:
            - mongo
        volumes:
            - .:/usr/src/app
    mongo:
        container_name: "mymongodatabase"
        image: mongo
        ports:
            - "27017:27017"
        logging:
            driver: none
        volumes:
            - ./mongo_data:/data/db